steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['builds', 'submit', '$_CLOUD_BUILD_JOB_PATH',  '--config=$_CLOUD_BUILD_JOB_PATH/cloudbuild.yaml', '--substitutions=COMMIT_SHA=$COMMIT_SHA']
      id: 'build-module'
substitutions:
    _CLOUD_BUILD_JOB_PATH: 'webcam'
timeout: 37000s