steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/$_DOCKER_IMAGE_ID'
substitutions:
  _DOCKER_IMAGE_ID: 'edgeml-webcam'